### ISSUE TITLE
sometimes values are not correctly applied

### ISSUE THREAD

**Issue by aufkrawall** [grmat/amdgpu-fancontrol#19] opened 2019-12-29 14:16 UTC
Hello,
my config e.g. looks like this:
```
HYSTERESIS=6000 
SLEEP_INTERVAL=1

TEMPS=( 65000  80000  90000 )
PWMS=(     80    140    200 )
```
So I think the fan speed should not be lowered until the temperature falls more than 6°C. But this is for some odd reason sometimes not the case (I don't know how that `...skipping...` thing ended up there in `journalctl`):

```
Dez 29 14:59:56 USER-linux amdgpu-fancontrol[40029]: current temp: 62000
Dez 29 14:59:56 USER-linux amdgpu-fancontrol[40029]: current pwm: 76, requested to set pwm to 80
Dez 29 14:59:56 USER-linux amdgpu-fancontrol[40029]: current pwm: 76, requested to set pwm to 80
Dez 29 14:59:56 USER-linux amdgpu-fancontrol[40029]: temp at last change was 63000
Dez 29 14:59:56 USER-linux amdgpu-fancontrol[40029]: changing pwm to 80
...skipping...
Dez 29 14:59:28 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 79000 is: 136
Dez 29 14:59:28 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 136
Dez 29 14:59:28 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 136
Dez 29 14:59:28 USER-linux amdgpu-fancontrol[40029]: temp at last change was 80000
Dez 29 14:59:28 USER-linux amdgpu-fancontrol[40029]: changing pwm to 136
Dez 29 14:59:29 USER-linux amdgpu-fancontrol[40029]: current temp: 80000
Dez 29 14:59:29 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 80000 is: 140
Dez 29 14:59:29 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 140
Dez 29 14:59:29 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 140
Dez 29 14:59:29 USER-linux amdgpu-fancontrol[40029]: temp at last change was 79000
Dez 29 14:59:29 USER-linux amdgpu-fancontrol[40029]: changing pwm to 140
Dez 29 14:59:30 USER-linux amdgpu-fancontrol[40029]: current temp: 80000
Dez 29 14:59:30 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 80000 is: 140
Dez 29 14:59:30 USER-linux amdgpu-fancontrol[40029]: current pwm: 135, requested to set pwm to 140
Dez 29 14:59:30 USER-linux amdgpu-fancontrol[40029]: current pwm: 135, requested to set pwm to 140
Dez 29 14:59:30 USER-linux amdgpu-fancontrol[40029]: temp at last change was 80000
Dez 29 14:59:30 USER-linux amdgpu-fancontrol[40029]: changing pwm to 140
Dez 29 14:59:31 USER-linux amdgpu-fancontrol[40029]: current temp: 80000
Dez 29 14:59:31 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 80000 is: 140
Dez 29 14:59:31 USER-linux amdgpu-fancontrol[40029]: current pwm: 135, requested to set pwm to 140
Dez 29 14:59:31 USER-linux amdgpu-fancontrol[40029]: current pwm: 135, requested to set pwm to 140
Dez 29 14:59:31 USER-linux amdgpu-fancontrol[40029]: temp at last change was 80000
Dez 29 14:59:31 USER-linux amdgpu-fancontrol[40029]: changing pwm to 140
Dez 29 14:59:32 USER-linux amdgpu-fancontrol[40029]: current temp: 79000
Dez 29 14:59:32 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 79000 is: 136
Dez 29 14:59:32 USER-linux amdgpu-fancontrol[40029]: current pwm: 135, requested to set pwm to 136
Dez 29 14:59:32 USER-linux amdgpu-fancontrol[40029]: temp at last change was 80000
Dez 29 14:59:32 USER-linux amdgpu-fancontrol[40029]: changing pwm to 136
Dez 29 14:59:33 USER-linux amdgpu-fancontrol[40029]: current temp: 78000
Dez 29 14:59:33 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 78000 is: 132
Dez 29 14:59:33 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 132
Dez 29 14:59:33 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 132
Dez 29 14:59:33 USER-linux amdgpu-fancontrol[40029]: not changing pwm, we just did at 79000, next change when below 73000
Dez 29 14:59:34 USER-linux amdgpu-fancontrol[40029]: current temp: 78000
Dez 29 14:59:34 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 78000 is: 132
Dez 29 14:59:34 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 132
Dez 29 14:59:34 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 132
Dez 29 14:59:34 USER-linux amdgpu-fancontrol[40029]: not changing pwm, we just did at 79000, next change when below 73000
Dez 29 14:59:35 USER-linux amdgpu-fancontrol[40029]: current temp: 79000
Dez 29 14:59:35 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 79000 is: 136
Dez 29 14:59:35 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 136
Dez 29 14:59:35 USER-linux amdgpu-fancontrol[40029]: temp at last change was 79000
Dez 29 14:59:35 USER-linux amdgpu-fancontrol[40029]: changing pwm to 136
Dez 29 14:59:36 USER-linux amdgpu-fancontrol[40029]: current temp: 71000
Dez 29 14:59:36 USER-linux amdgpu-fancontrol[40029]: interpolated pwm value for temperature 71000 is: 104
Dez 29 14:59:36 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 104
Dez 29 14:59:36 USER-linux amdgpu-fancontrol[40029]: current pwm: 132, requested to set pwm to 104
Dez 29 14:59:36 USER-linux amdgpu-fancontrol[40029]: temp at last change was 79000
Dez 29 14:59:36 USER-linux amdgpu-fancontrol[40029]: changing pwm to 104
```
As you can see, somehow the the interpolated values and the values that are returned as active afterwards don't match, leading to a  constant change of fan speed around 80°C.

Also visible in other programs:
![fan](https://user-images.githubusercontent.com/13510490/71557946-c4c03280-2a4d-11ea-99ae-423ff003d405.png)

Now question is: Does the script apply incorrect value, or is there a bug in the driver that prevents applying the correct values? And if it's the latter one, perhaps it can be worked around by e.g. skipping every xth PWM step? On Windows, this behavior does not occur with MSI Afterburner.

Thanks!

**Comment by grmat** [comment] 2019-12-29 15:12
> Now question is: Does the script apply incorrect value, or is there a bug in the driver that prevents applying the correct values?

This has been seen earlier, e.g. in #2. Sometimes the actual pwm value doesn't correspond to the previously requested value. You can confirm that by manually writing a value to sysfs and then read it later.

I'm not sure if I'd call it a driver bug, but I think the issue is that the PWM value is mapped to [0-255], but there aren't actually 256 distinct PWM values. The value then "jumps" to the next match.

Working around that would be possible, but I consider that out of scope for this project.

**Comment by aufkrawall** [comment] 2019-12-29 17:53
Alright. It's not optimal, but given the rather minor divergence, I think it's at least bearable (especially with better fans). I suppose no other userspace control approach takes this into consideration either.

Perhaps I'll report it to AMD. Feel free to close and thanks again!

**Comment by grmat** [comment] 2019-12-31 14:28
I've pushed [pwmtest](https://github.com/grmat/amdgpu-fancontrol/blob/pwmtest/pwmtest) to verify the previous assumption. It sets all possible PWM values from 0-255 and reads the value back. Both values are output in csv format.

You could try to run it if you want to investigate further or file an amdgpu issue

**Comment by aufkrawall** [comment] 2019-12-31 14:44
```
./pwmtest /sys/class/drm/card0/device/hwmon/hwmon0/pwm1
requested,actual
0,0
1,0
2,0
3,0
4,0
5,0
6,2
7,2
8,5
9,5
10,5
11,7
12,7
13,10
14,10
15,10
16,12
17,12
18,15
19,15
20,15
21,17
22,17
23,20
24,20
25,20
26,22
27,22
28,22
29,25
30,25
31,28
32,28
33,28
34,30
35,30
36,33
37,33
38,33
39,35
40,35
41,38
42,38
43,38
44,40
45,40
46,43
47,43
48,43
49,45
50,45
51,51
52,51
53,51
54,51
55,51
56,51
57,53
58,53
59,56
60,56
61,56
62,58
63,58
64,61
65,61
66,61
67,63
68,63
69,66
70,66
71,66
72,68
73,68
74,71
75,71
76,71
77,73
78,73
79,73
80,76
81,76
82,79
83,79
84,79
85,81
86,81
87,84
88,84
89,84
90,86
91,86
92,89
93,89
94,89
95,91
96,91
97,94
98,94
99,94
100,96
101,96
102,102
103,102
104,102
105,102
106,102
107,102
108,104
109,104
110,107
111,107
112,107
113,109
114,109
115,112
116,112
117,112
118,114
119,114
120,117
121,117
122,117
123,119
124,119
125,122
126,122
127,122
128,124
129,124
130,124
131,127
132,127
133,130
134,130
135,130
136,132
137,132
138,135
139,135
140,135
141,137
142,137
143,140
144,140
145,140
146,142
147,142
148,145
149,145
150,145
151,147
152,147
153,153
154,153
155,153
156,153
157,153
158,153
159,155
160,155
161,158
162,158
163,158
164,160
165,160
166,163
167,163
168,163
169,165
170,165
171,168
172,168
173,168
174,170
175,170
176,173
177,173
178,173
179,175
180,175
181,175
182,178
183,178
184,181
185,181
186,181
187,183
188,183
189,186
190,186
191,186
192,188
193,188
194,191
195,191
196,191
197,193
198,193
199,196
200,196
201,196
202,198
203,198
204,204
205,204
206,204
207,204
208,204
209,204
210,206
211,206
212,209
213,209
214,209
215,211
216,211
217,214
218,214
219,214
220,216
221,216
222,219
223,219
224,219
225,221
226,221
227,224
228,224
229,224
230,226
231,226
232,226
233,229
234,229
235,232
236,232
237,232
238,234
239,234
240,237
241,237
242,237
243,239
244,239
245,242
246,242
247,242
248,244
249,244
250,247
251,247
252,247
253,249
254,249
255,255
```

**Comment by grmat** [comment] 2019-12-31 14:49
OK. Those are actually just 96 instead of 256 distinct values. I've also taken a closer and can say that a workaround for the hysteresis function wouldn't be much effort. I'm keeping this one open and might fix it sometime.

**Comment by grmat** [comment] 2019-12-31 15:07
You could check if https://github.com/grmat/amdgpu-fancontrol/blob/pwmtest/amdgpu-fancontrol works better for you

**Comment by aufkrawall** [comment] 2019-12-31 15:20
It seems this already did the trick. Despite of minor temperature deviations, the fan speed never got decreased due to this:
![Screenshot_20191231_161451](https://user-images.githubusercontent.com/13510490/71625604-ffaa9d80-2be8-11ea-9237-8900dea2de21.png)

Unless there isn't something I'm not aware of, I'd say that the script works perfectly fine now, i.e. fan reacts completely as expected. Great. :)
Gonna give it a try on the aforementioned Navi card too.

**Comment by aufkrawall** [comment] 2019-12-31 19:13
There is a bug in the driver with Navi, the sysfs sensor always returns 0rpm when setting it to custom speed.
However, this seems to be just a cosmetic issue, as the fan is fully controllable. That being said and judging by my ears, the script seems to work as expected on Navi.

**Comment by grmat** [comment] 2019-12-31 19:18
Thanks

**Closed by grmat** 2019-12-31 19:18 UTC
